name: '$(BuildDefinitionName)_$(nextVersion)$(Rev:.r)'

trigger:
- '*'

pool:
  vmImage: 'windows-2019'

variables:
  nextVersion: '3.0'
  buildProjects: '**/*.csproj'
  buildConfiguration: 'Release'
  testProjects: '**/*[Tt]ests/*.csproj'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '$(buildProjects)'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '$(buildProjects)'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '$(testProjects)'
    arguments: '--configuration $(BuildConfiguration)'

- task: PublishBuildArtifacts@1
  displayName: Publish
  inputs:
    ArtifactName: 'drop'
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()